// <auto-generated />
using System;
using DigitalArs.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalArs.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904051533_SeedUsersAndMovements")]
    partial class SeedUsersAndMovements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalArs.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Money")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBlocked = false,
                            Money = 500000.00m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBlocked = false,
                            Money = 260000.00m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBlocked = false,
                            Money = 185000.50m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBlocked = false,
                            Money = 45230.50m,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBlocked = false,
                            Money = 320000.00m,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBlocked = false,
                            Money = 410000.00m,
                            UserId = 6
                        });
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "seed-role-admin-concurrency",
                            Description = "Administrador con permisos elevados para gestionar usuarios",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "seed-role-user-concurrency",
                            Description = "Usuario estandar de la billetera virtual",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Concept")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("ToAccountId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Date");

                    b.HasIndex("ToAccountId");

                    b.ToTable("Transactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 4,
                            Amount = 43730.50m,
                            Concept = "Depósito inicial de fondos",
                            Date = new DateTime(2026, 8, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            Amount = 239000.00m,
                            Concept = "Depósito inicial",
                            Date = new DateTime(2026, 8, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 3,
                            Amount = 193500.50m,
                            Concept = "Depósito inicial",
                            Date = new DateTime(2026, 8, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 5,
                            Amount = 340000.00m,
                            Concept = "Depósito inicial",
                            Date = new DateTime(2026, 8, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 6,
                            Amount = 404000.00m,
                            Concept = "Depósito inicial",
                            Date = new DateTime(2026, 8, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 4,
                            Amount = 15000.00m,
                            Concept = "Transferencia enviada a Roberto Carlos",
                            Date = new DateTime(2026, 8, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            ToAccountId = 2,
                            Type = 3
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 2,
                            Amount = 15000.00m,
                            Concept = "Transferencia recibida de Alejandro Silva",
                            Date = new DateTime(2026, 8, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            ToAccountId = 4,
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 5,
                            Amount = 25000.00m,
                            Concept = "Transferencia enviada a Alejandro Silva",
                            Date = new DateTime(2026, 8, 18, 11, 15, 0, 0, DateTimeKind.Utc),
                            ToAccountId = 4,
                            Type = 3
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 4,
                            Amount = 25000.00m,
                            Concept = "Transferencia recibida de Micaela Mulato",
                            Date = new DateTime(2026, 8, 18, 11, 15, 0, 0, DateTimeKind.Utc),
                            ToAccountId = 5,
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 4,
                            Amount = 12000.00m,
                            Concept = "Transferencia enviada a Emmanuel Torres",
                            Date = new DateTime(2026, 8, 25, 16, 45, 0, 0, DateTimeKind.Utc),
                            ToAccountId = 6,
                            Type = 3
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 6,
                            Amount = 12000.00m,
                            Concept = "Transferencia recibida de Alejandro Silva",
                            Date = new DateTime(2026, 8, 25, 16, 45, 0, 0, DateTimeKind.Utc),
                            ToAccountId = 4,
                            Type = 2
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 4,
                            Amount = 5000.00m,
                            Concept = "Transferencia enviada a Micaela Mulato",
                            Date = new DateTime(2026, 9, 1, 18, 20, 0, 0, DateTimeKind.Utc),
                            ToAccountId = 5,
                            Type = 3
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 5,
                            Amount = 5000.00m,
                            Concept = "Transferencia recibida de Alejandro Silva",
                            Date = new DateTime(2026, 9, 1, 18, 20, 0, 0, DateTimeKind.Utc),
                            ToAccountId = 4,
                            Type = 2
                        },
                        new
                        {
                            Id = 14,
                            AccountId = 3,
                            Amount = 8500.00m,
                            Concept = "Transferencia enviada a Alejandro Silva",
                            Date = new DateTime(2026, 9, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            ToAccountId = 4,
                            Type = 3
                        },
                        new
                        {
                            Id = 15,
                            AccountId = 4,
                            Amount = 8500.00m,
                            Concept = "Transferencia recibida de Mohammed Khan",
                            Date = new DateTime(2026, 9, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            ToAccountId = 3,
                            Type = 2
                        },
                        new
                        {
                            Id = 16,
                            AccountId = 6,
                            Amount = 6000.00m,
                            Concept = "Transferencia enviada a Roberto Carlos",
                            Date = new DateTime(2026, 9, 3, 9, 30, 0, 0, DateTimeKind.Utc),
                            ToAccountId = 2,
                            Type = 3
                        },
                        new
                        {
                            Id = 17,
                            AccountId = 2,
                            Amount = 6000.00m,
                            Concept = "Transferencia recibida de Emmanuel Torres",
                            Date = new DateTime(2026, 9, 3, 9, 30, 0, 0, DateTimeKind.Utc),
                            ToAccountId = 6,
                            Type = 2
                        });
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-admin-concurrency",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@digitalars.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            IsDeleted = false,
                            LastName = "DigitalArs",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@DIGITALARS.COM",
                            NormalizedUserName = "ADMIN@DIGITALARS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENO87HGO7ibu/kR6bblZLBu39LF1P9oeSEu7bwGb0YRvny7KouBk+XFrlxztTvecMQ==",
                            PhoneNumberConfirmed = false,
                            RoleId = 1,
                            SecurityStamp = "SEED-ADMIN-SECURITY-STAMP",
                            TwoFactorEnabled = false,
                            UserName = "admin@digitalars.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-user1-concurrency",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "robercarlos3@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Roberto",
                            IsDeleted = false,
                            LastName = "Carlos",
                            LockoutEnabled = false,
                            NormalizedEmail = "ROBERCARLOS3@GMAIL.COM",
                            NormalizedUserName = "ROBERCARLOS3@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELKOHh9OA8J6+VbOTSSbRWvcAbbwaPQ9dZcgFx02YAC1LeN/DPShnsiygednoXJUNQ==",
                            PhoneNumberConfirmed = false,
                            RoleId = 2,
                            SecurityStamp = "SEED-USER1-SECURITY-STAMP",
                            TwoFactorEnabled = false,
                            UserName = "robercarlos3@gmail.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-user2-concurrency",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mokha@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mohammed",
                            IsDeleted = false,
                            LastName = "Khan",
                            LockoutEnabled = false,
                            NormalizedEmail = "MOKHA@GMAIL.COM",
                            NormalizedUserName = "MOKHA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEErdfRgSxQZB1799p6YXG2T/bLL4bqGYPBRcYHsKas3tZrZUfw1cn6bK9oGtgvtkhA==",
                            PhoneNumberConfirmed = false,
                            RoleId = 2,
                            SecurityStamp = "SEED-USER2-SECURITY-STAMP",
                            TwoFactorEnabled = false,
                            UserName = "mokha@gmail.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-user4-concurrency",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alejandro.silva@digitalars.com",
                            EmailConfirmed = true,
                            FirstName = "Alejandro",
                            IsDeleted = false,
                            LastName = "Silva",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALEJANDRO.SILVA@DIGITALARS.COM",
                            NormalizedUserName = "ALEJANDRO.SILVA@DIGITALARS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIF4BH6BgJcp+Hmu8tYbCiyDyfC8/R3A8lus7ILAex/9qAxhI8YRaq7+ERYrGrRrYg==",
                            PhoneNumberConfirmed = false,
                            RoleId = 2,
                            SecurityStamp = "SEED-USER4-SECURITY-STAMP",
                            TwoFactorEnabled = false,
                            UserName = "alejandro.silva@digitalars.com"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-user5-concurrency",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "micaela.mulato@digitalars.com",
                            EmailConfirmed = true,
                            FirstName = "Micaela",
                            IsDeleted = false,
                            LastName = "Mulato",
                            LockoutEnabled = false,
                            NormalizedEmail = "MICAELA.MULATO@DIGITALARS.COM",
                            NormalizedUserName = "MICAELA.MULATO@DIGITALARS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPlWIfeBvEa2UIgXOAlJgZkhZ9W+6n3zxsEIiVncqS9jY+6qmsMbOL+u+DeaM10S1w==",
                            PhoneNumberConfirmed = false,
                            RoleId = 2,
                            SecurityStamp = "SEED-USER5-SECURITY-STAMP",
                            TwoFactorEnabled = false,
                            UserName = "micaela.mulato@digitalars.com"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-user6-concurrency",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "emmanuel.torres@digitalars.com",
                            EmailConfirmed = true,
                            FirstName = "Emmanuel",
                            IsDeleted = false,
                            LastName = "Torres",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMMANUEL.TORRES@DIGITALARS.COM",
                            NormalizedUserName = "EMMANUEL.TORRES@DIGITALARS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEISvy59LTmpoZ20JI0rhgziQdnw7hg1vq272APTffUCeMWtHb8rAl0V5Src75EltPA==",
                            PhoneNumberConfirmed = false,
                            RoleId = 2,
                            SecurityStamp = "SEED-USER6-SECURITY-STAMP",
                            TwoFactorEnabled = false,
                            UserName = "emmanuel.torres@digitalars.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.Account", b =>
                {
                    b.HasOne("DigitalArs.Domain.Entities.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("DigitalArs.Domain.Entities.Account", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("DigitalArs.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalArs.Domain.Entities.Account", "ToAccount")
                        .WithMany()
                        .HasForeignKey("ToAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("ToAccount");
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.User", b =>
                {
                    b.HasOne("DigitalArs.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("DigitalArs.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("DigitalArs.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("DigitalArs.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("DigitalArs.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalArs.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("DigitalArs.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DigitalArs.Domain.Entities.User", b =>
                {
                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
